on:
  workflow_dispatch:
jobs:
  testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/deploy-user
    steps:
      - name: Choosing folder
        run: echo "The PR was merged" > test.txt
      - name: Adding file
        run: echo "The PR was merged" > test.txt
