on:
  workflow_dispatch:
jobs:
  testing:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /usr/share/docker/webapp/PR-bot
    steps:
      - name: Updating repo
        run: git pull
      - name: Stopping existing container
        run: docker container stop webappcont
        continue-on-error: True
      - name: Removing existing container
        run: docker container rm webappcont
        continue-on-error: True
      - name: Removing existing image
        run: docker image rm webapp
        continue-on-error: True
      - name: Building image
        run: docker build -t webapp .
      - name: Starting container
        run: docker run --name webappcont -d -p 443:443 -it webapp:latest /usr/share/nginx/html/application/start.sh
      - name: Executing nginx
        run: docker exec -it webappcont nginx
