on:
  workflow_dispatch:
jobs:
  testing:
    runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: /home/deploy-user
    steps:
      - name: Choosing folder
        run: ls
      - name: finding
        run: find /*.*
      - name: Adding file
        run: echo "The PR was merged" > test.txt
